version: '3.7'

services:
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_DATABASE: 'jobs'
      MONGO_INITDB_ROOT_USERNAME: jobs
      MONGO_INITDB_ROOT_PASSWORD: jobs
    ports:
      - 27017:27017
